### ISSUE TITLE
build sucess but run error?

### ISSUE THREAD

**Issue by westeast** [ApolloAuto/apollo-platform#19]
./build.sh build 
result:
```
<== Finished processing package [231 of 231]: 'xacro'
============================
[ OK ] Build ros succeed!
============================
```

run roscore 
```
Traceback (most recent call last):
  File "/home/westeast/git/indigo/src/install/ros_x86_64/bin/roscore", line 36, in <module>
    from rosmaster.master_api import NUM_WORKERS
  File "/home/westeast/git/indigo/src/install/ros_x86_64/lib/python2.7/dist-packages/rosmaster/__init__.py", line 35, in <module>
    from .main import rosmaster_main
  File "/home/westeast/git/indigo/src/install/ros_x86_64/lib/python2.7/dist-packages/rosmaster/main.py", line 43, in <module>
    import rosmaster.master
  File "/home/westeast/git/indigo/src/install/ros_x86_64/lib/python2.7/dist-packages/rosmaster/master.py", line 45, in <module>
    import rosgraph.xmlrpc
  File "/home/westeast/git/indigo/src/install/ros_x86_64/lib/python2.7/dist-packages/rosgraph/__init__.py", line 36, in <module>
    from . masterapi import Master, MasterFailure, MasterError, MasterException
  File "/home/westeast/git/indigo/src/install/ros_x86_64/lib/python2.7/dist-packages/rosgraph/masterapi.py", line 49, in <module>
    from rospy.impl.broadcast_manager import BroadcastManager
  File "/home/westeast/git/indigo/src/install/ros_x86_64/lib/python2.7/dist-packages/rospy/__init__.py", line 49, in <module>
    from .client import spin, myargv, init_node, \
  File "/home/westeast/git/indigo/src/install/ros_x86_64/lib/python2.7/dist-packages/rospy/client.py", line 60, in <module>
    import rospy.impl.init
  File "/home/westeast/git/indigo/src/install/ros_x86_64/lib/python2.7/dist-packages/rospy/impl/init.py", line 54, in <module>
    from .tcpros import init_tcpros
  File "/home/westeast/git/indigo/src/install/ros_x86_64/lib/python2.7/dist-packages/rospy/impl/tcpros.py", line 45, in <module>
    import rospy.impl.tcpros_service
  File "/home/westeast/git/indigo/src/install/ros_x86_64/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 65, in <module>
    from broadcast_manager import BroadcastManager
  File "/home/westeast/git/indigo/src/install/ros_x86_64/lib/python2.7/dist-packages/rospy/impl/broadcast_manager.py", line 58, in <module>
    from rospy.impl import participant
  File "/home/westeast/git/indigo/src/install/ros_x86_64/lib/python2.7/dist-packages/rospy/impl/participant.py", line 28, in <module>
    _participant = swig_import_helper()
  File "/home/westeast/git/indigo/src/install/ros_x86_64/lib/python2.7/dist-packages/rospy/impl/participant.py", line 20, in swig_import_helper
    import _participant
ImportError: /home/westeast/git/indigo/src/install/ros_x86_64/lib/_participant.so: undefined symbol: _ZN3ros11Participant8read_msgEv
```

**Comment by quning78** [comment]
Have you source the setup.bash first in the installed directory?

**Comment by westeast** [comment]
@quning78 have source the setup.bash.  and I rebuild the third_party/swig_wrapper   and fix the problem

but I have another problem when run roscore 

```
system/indigo/src/install/ros_x86_64/lib/rosout/rosout: symbol lookup error: system/indigo/src/install/ros_x86_64/lib/librosconsole_log4cxx.so: undefined symbol: _ZN7log4cxx16AppenderSkeleton9setOptionERKSsS2_

```

**Comment by westeast** [comment]
@quning78 rosconsole_log4cxx.so is also in third_party  and I have rebuild it .

**Comment by westeast** [comment]
I delete the rosconsole*.lib and run roscore sucessfully

**Comment by echotor** [comment]
@westeast 你好，请问你怎么解决这个问题，我也遇到了，但是我重新编译了_participant.so这个库也没用

**Comment by sychaichangkun** [comment]
@westeast  Hello, I met the problem 
`system/indigo/src/install/ros_x86_64/lib/rosout/rosout: symbol lookup error: system/indigo/src/install/ros_x86_64/lib/librosconsole_log4cxx.so: undefined symbol: _ZN7log4cxx16AppenderSkeleton9setOptionERKSsS2_
`.
and  I try to delete rosconsole*.lib as you mentioned,  but can't find where it is.
Could you please explain it?

**Comment by GitBubble** [comment]
> system/indigo/src/install/ros_x86_64/lib/rosout/rosout: symbol lookup error: system/indigo/src/install/ros_x86_64/lib/librosconsole_log4cxx.so: undefined symbol: _ZN7log4cxx16AppenderSkeleton9setOptionERKSsS2_

this is really a annoying bug and still not fixed  but closed .... amazing... :p

i open a new issue here #62  , here is the PR  #63
